PROG=	test_s3
SRCS=	main.c
MAN1=

# Useful relative directories
LIBCPERCIVA_DIR	=	../../libcperciva
LIB_DIR	=	../../lib

# libcperciva includes
IDIRS	+=	-I ${LIBCPERCIVA_DIR}/events
IDIRS	+=	-I ${LIBCPERCIVA_DIR}/util

# kivaloo includes
IDIRS	+=	-I ${LIB_DIR}/proto_s3
IDIRS	+=	-I ${LIB_DIR}/util

# Debugging options
#CFLAGS	+=	-g
#CFLAGS	+=	-DNDEBUG
#CFLAGS	+=	-DDEBUG
#CFLAGS	+=	-pg

test:	all
	@./test_s3.sh

CLEANFILES+=	s3.leak ktrace-s3.out kdump-s3.out
CLEANFILES+=	test_s3.leak ktrace-test_s3.out kdump-test_s3.out
CLEANFILES+=	s3.log

.include <bsd.prog.mk>
