PROG=	test_mux
SRCS=	main.c
MAN1=

# Useful relative directories
LIBCPERCIVA_DIR	=	../../libcperciva
LIB_DIR	=	../../lib

# libcperciva includes
IDIRS	+=	-I ${LIBCPERCIVA_DIR}/events
IDIRS	+=	-I ${LIBCPERCIVA_DIR}/util

# kivaloo includes
IDIRS	+=	-I ${LIB_DIR}/datastruct
IDIRS	+=	-I ${LIB_DIR}/proto_kvlds
IDIRS	+=	-I ${LIB_DIR}/util

# Debugging options
#CFLAGS	+=	-g
#CFLAGS	+=	-DNDEBUG
#CFLAGS	+=	-DDEBUG
#CFLAGS	+=	-pg

test:	all
	@/bin/sh test_mux.sh

CLEANFILES+=	mux.leak

.include <bsd.prog.mk>
