PROG=	test_kvlds
.PATH.c	:	../kvlds
SRCS=	main.c
MAN1=

# Useful relative directories
LIBCPERCIVA_DIR	=	../../libcperciva
LIB_DIR	=	../../lib

# libcperciva includes
IDIRS	+=	-I ${LIBCPERCIVA_DIR}/events
IDIRS	+=	-I ${LIBCPERCIVA_DIR}/util

# kivaloo includes
IDIRS	+=	-I ${LIB_DIR}/datastruct
IDIRS	+=	-I ${LIB_DIR}/proto_kvlds
IDIRS	+=	-I ${LIB_DIR}/util

# Debugging options
#CFLAGS	+=	-g
#CFLAGS	+=	-DNDEBUG
#CFLAGS	+=	-DDEBUG
#CFLAGS	+=	-pg

test:	all
	@./test_kvlds.sh

CLEANFILES+=	dynamodb-kv.log

.include <bsd.prog.mk>
