PROG=	test_kvlds
.PATH.c	:	../kvlds
SRCS=	main.c
MAN1=

# Useful relative directories
LIBCPERCIVA_DIR	=	../../libcperciva
LIB_DIR	=	../../lib

# CPU features detection
.PATH.c	:	${LIBCPERCIVA_DIR}/cpusupport
SRCS	+=	cpusupport_x86_crc32.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/cpusupport

# Data structures (libcperciva)
.PATH.c	:	${LIBCPERCIVA_DIR}/datastruct
SRCS	+=	elasticarray.c
SRCS	+=	ptrheap.c
SRCS	+=	timerqueue.c
SRCS	+=	elasticqueue.c
SRCS	+=	seqptrmap.c
IDIRS	+=	-I ${LIBCPERCIVA_DIR}/datastruct

# Data structures
.PATH.c	:	${LIB_DIR}/datastruct
SRCS	+=	kvldskey.c
IDIRS	+=	-I ${LIB_DIR}/datastruct

# Utility functions
.PATH.c	:	${LIBCPERCIVA_DIR}/util
SRCS	+=	monoclock.c
SRCS	+=	sock.c
SRCS	+=	warnp.c
IDIRS	+=	-I ${LIBCPERCIVA_DIR}/util

# Fundamental algorithms
.PATH.c	:	${LIBCPERCIVA_DIR}/alg
SRCS	+=	crc32c.c
SRCS	+=	crc32c_sse42.c
IDIRS	+=	-I ${LIBCPERCIVA_DIR}/alg

# Event loop
.PATH.c	:	${LIBCPERCIVA_DIR}/events
SRCS	+=	events_immediate.c
SRCS	+=	events_network.c
SRCS	+=	events_network_selectstats.c
SRCS	+=	events_timer.c
SRCS	+=	events.c
IDIRS	+=	-I ${LIBCPERCIVA_DIR}/events

# Event-driven networking
.PATH.c	:	${LIBCPERCIVA_DIR}/network
SRCS	+=	network_read.c
SRCS	+=	network_write.c
IDIRS	+=	-I ${LIBCPERCIVA_DIR}/network


# Buffered networking
.PATH.c	:	${LIB_DIR}/netbuf
SRCS	+=	netbuf_read.c
SRCS	+=	netbuf_write.c
IDIRS	+=	-I ${LIB_DIR}/netbuf

# Wire protocol
.PATH.c	:	${LIB_DIR}/wire
SRCS	+=	wire_packet.c
SRCS	+=	wire_readpacket.c
SRCS	+=	wire_writepacket.c
SRCS	+=	wire_requestqueue.c
IDIRS	+=	-I ${LIB_DIR}/wire

# LBS request/response packets
.PATH.c	:	${LIB_DIR}/proto_kvlds
SRCS	+=	proto_kvlds_client.c
IDIRS	+=	-I ${LIB_DIR}/proto_kvlds

# Debugging options
#CFLAGS	+=	-g
#CFLAGS	+=	-DNDEBUG
#CFLAGS	+=	-DDEBUG
#CFLAGS	+=	-pg

cflags-crc32c_sse42.o:
	@echo '$${CFLAGS_X86_CRC32}'

test:	all
	@./test_kvlds.sh

CLEANFILES+=	dynamodb-kv.log

.include <bsd.prog.mk>
