PROG=	test_kvlds_blocking
SRCS=	main.c
MAN1=

# Useful relative directories
LIBCPERCIVA_DIR	=	../../libcperciva
LIB_DIR	=	../../lib

# libcperciva includes
IDIRS	+=	-I ${LIBCPERCIVA_DIR}/events
IDIRS	+=	-I ${LIBCPERCIVA_DIR}/util

# kivaloo includes
IDIRS	+=	-I ${LIB_DIR}/datastruct
IDIRS	+=	-I ${LIB_DIR}/proto_kvlds
IDIRS	+=	-I ${LIB_DIR}/util

test:	all
	@./test_kvlds_blocking.sh

.include <bsd.prog.mk>
