PROG=	test_lbs
SRCS=	main.c
MAN1=

# Useful relative directories
LIBCPERCIVA_DIR	=	../../libcperciva
LIB_DIR	=	../../lib

# CPU features detection
.PATH.c	:	${LIBCPERCIVA_DIR}/cpusupport
SRCS	+=	cpusupport_x86_crc32_64.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/cpusupport

# Data structures
.PATH.c	:	${LIBCPERCIVA_DIR}/datastruct
SRCS	+=	elasticarray.c
SRCS	+=	ptrheap.c
SRCS	+=	timerqueue.c
SRCS	+=	elasticqueue.c
SRCS	+=	seqptrmap.c
IDIRS	+=	-I ${LIBCPERCIVA_DIR}/datastruct

# Utility functions
.PATH.c	:	${LIBCPERCIVA_DIR}/util
SRCS	+=	monoclock.c
SRCS	+=	sock.c
SRCS	+=	warnp.c
IDIRS	+=	-I ${LIBCPERCIVA_DIR}/util

# Fundamental algorithms
.PATH.c	:	${LIBCPERCIVA_DIR}/alg
SRCS	+=	crc32c.c
SRCS	+=	crc32c_sse42.c
IDIRS	+=	-I ${LIBCPERCIVA_DIR}/alg

# Event loop
.PATH.c	:	${LIBCPERCIVA_DIR}/events
SRCS	+=	events_immediate.c
SRCS	+=	events_network.c
SRCS	+=	events_network_selectstats.c
SRCS	+=	events_timer.c
SRCS	+=	events.c
IDIRS	+=	-I ${LIBCPERCIVA_DIR}/events

# Event-driven networking
.PATH.c	:	${LIBCPERCIVA_DIR}/network
SRCS	+=	network_read.c
SRCS	+=	network_write.c
IDIRS	+=	-I ${LIBCPERCIVA_DIR}/network

# Buffered networking
.PATH.c	:	${LIB_DIR}/netbuf
SRCS	+=	netbuf_read.c
SRCS	+=	netbuf_write.c
IDIRS	+=	-I ${LIB_DIR}/netbuf

# Wire protocol
.PATH.c	:	${LIB_DIR}/wire
SRCS	+=	wire_packet.c
SRCS	+=	wire_readpacket.c
SRCS	+=	wire_writepacket.c
SRCS	+=	wire_requestqueue.c
IDIRS	+=	-I ${LIB_DIR}/wire

# Utility functions
.PATH.c	:	${LIB_DIR}/util
SRCS	+=	kivaloo.c
IDIRS	+=	-I ${LIB_DIR}/util

# LBS request/response packets
.PATH.c	:	${LIB_DIR}/proto_lbs
SRCS	+=	proto_lbs_client.c
IDIRS	+=	-I ${LIB_DIR}/proto_lbs

# Debugging options
#CFLAGS	+=	-g
#CFLAGS	+=	-DNDEBUG
#CFLAGS	+=	-DDEBUG
#CFLAGS	+=	-pg

test:	all
	@./test_lbs.sh

CLEANFILES+=	lbs.leak test_lbs.leak

.include <bsd.prog.mk>
