PROG=	test_s3
SRCS=	main.c

# Useful relative directories
LIBCPERCIVA_DIR	=	../../libcperciva
LIB_DIR	=	../../lib

# libcperciva imports
IDIRS	+=	-I ${LIBCPERCIVA_DIR}/aws
IDIRS	+=	-I ${LIBCPERCIVA_DIR}/events
IDIRS	+=	-I ${LIBCPERCIVA_DIR}/http
IDIRS	+=	-I ${LIBCPERCIVA_DIR}/util

# kivaloo imports
IDIRS	+=	-I ${LIB_DIR}/s3

CFLAGS	+=	-g

test:	test_s3
	./test_s3 ~/.s3/aws.key

.include <bsd.prog.mk>
