PROG=	kvlds-undump
SRCS=	main.c

# Libraries which are sometimes merged into libc
LDADD	=	-lrt
#LDADD	+=	-lxnet  # Missing on FreeBSD

# Useful relative directories
LIBCPERCIVA_DIR	=	../libcperciva
LIB_DIR	=	../lib

# libcperciva includes
IDIRS	+=	-I ${LIBCPERCIVA_DIR}/events
IDIRS	+=	-I ${LIBCPERCIVA_DIR}/util

# kivaloo includes
IDIRS	+=	-I ${LIB_DIR}/datastruct
IDIRS	+=	-I ${LIB_DIR}/util

.include <bsd.prog.mk>
