PROG=	mkpairs
SRCS=	main.c

# Useful relative directories
LIBCPERCIVA_DIR	=	../../libcperciva
BENCHLIB_DIR	=	../lib

# libcperciva imports
IDIRS	+=	-I ${LIBCPERCIVA_DIR}/util

# bench imports
IDIRS	+=	-I ${BENCHLIB_DIR}

# Debugging options
#CFLAGS	+=	-g
#CFLAGS	+=	-DNDEBUG
#CFLAGS	+=	-DDEBUG
#CFLAGS	+=	-pg

.include <bsd.prog.mk>
