PROG=	test_http
SRCS=	main.c

# Useful relative directories
LIBCPERCIVA_DIR	=	../../libcperciva
LIB_DIR	=	../../lib

# libcperciva imports
IDIRS	+=	-I ${LIBCPERCIVA_DIR}/events
IDIRS	+=	-I ${LIBCPERCIVA_DIR}/util

# kivaloo imports
IDIRS	+=	-I ${LIB_DIR}/http

CFLAGS	+=	-g

test:	test_http
	@./test_http.sh

.include <bsd.prog.mk>
