PROG=	test_serverpool
SRCS=	main.c

# Useful relative directories
LIBCPERCIVA_DIR	=	../../libcperciva
LIB_DIR	=	../../lib

# libcperciva imports
IDIRS	+=	-I ${LIBCPERCIVA_DIR}/events
IDIRS	+=	-I ${LIBCPERCIVA_DIR}/util

# kivaloo imports
IDIRS	+=	-I ${LIB_DIR}/serverpool

# Data structures
CFLAGS	+=	-g

test:	test_serverpool
	./test_serverpool dynamodb.us-east-1.amazonaws.com:80

.include <bsd.prog.mk>
