PROG=	test_network_ssl
SRCS=	main.c
MAN1=

# Library code required
LDADD_REQ	= -lssl -lcrypto

# Useful relative directories
LIBCPERCIVA_DIR	=	../../libcperciva
LIB_DIR	=	../../lib

# libcperciva imports
IDIRS	+=	-I ${LIBCPERCIVA_DIR}/events
IDIRS	+=	-I ${LIBCPERCIVA_DIR}/util

# kivaloo imports
IDIRS	+=	-I ${LIB_DIR}/network_ssl

test:	all
	@./test_network_ssl.sh

.include <bsd.prog.mk>
