PROG=	dynamodb_sign
SRCS=	main.c
MK_MAN=	no

# Libraries which are sometimes merged into libc
LDADD	=	-lrt
#LDADD	+=	-lxnet  # Missing on FreeBSD

# Useful relative directories
LIBCPERCIVA_DIR	=	../../libcperciva

# libcperciva imports
IDIRS	+=	-I ${LIBCPERCIVA_DIR}/aws
IDIRS	+=	-I ${LIBCPERCIVA_DIR}/util

test: all
	@./test_sign.sh

# Debugging options
#CFLAGS	+=	-g
#CFLAGS	+=	-DNDEBUG
#CFLAGS	+=	-DDEBUG
#CFLAGS	+=	-pg

.include <bsd.prog.mk>
