PROG=	test_https
SRCS=	main.c

# Useful relative directories
LIBCPERCIVA_DIR	=	../../libcperciva
LIB_DIR	=	../../lib

# Library code required
LDADD_REQ	= -lssl -lcrypto

# libcperciva imports
IDIRS	+=	-I ${LIBCPERCIVA_DIR}/events
IDIRS	+=	-I ${LIBCPERCIVA_DIR}/util

# kivaloo imports
IDIRS	+=	-I ${LIB_DIR}/http

test:	test_https
	@./test_https.sh

.include <bsd.prog.mk>
